const catalog = {
  phones: {
    brand: ["Apple", "Samsung", "Xiaomi"],
    model: ["iPhone 14", "Galaxy S23", "Redmi Note 12"],
    price: [999, 899, 499],
    features: ["5G", "OLED Display", "Fast Charging"],
    photo: ["iphone14.png", "galaxyS23.png", "redmiNote12.png"],
  },
  smartWatches: {
    brand: ["Apple", "Samsung", "Garmin"],
    model: ["Apple Watch 8", "Galaxy Watch 5", "Garmin Fenix 7"],
    price: [399, 299, 599],
    features: ["Heart Rate Monitor", "GPS", "Waterproof"],
    photo: ["appleWatch8.png", "galaxyWatch5.png", "garminFenix7.png"],
  },
  tV: {
    brand: ["LG", "Samsung", "Sony"],
    model: ["OLED C2", "QLED Q90", "Bravia XR"],
    price: [1299, 1099, 1499],
    features: ["4K", "HDR", "Smart TV"],
    photo: ["lgC2.png", "samsungQ90.png", "sonyBraviaXR.png"],
  },
  audio: {
    brand: ["Bose", "Sony", "JBL"],
    model: ["QuietComfort 45", "WH-1000XM5", "Flip 6"],
    price: [329, 399, 149],
    features: ["Noise Cancelling", "Wireless", "Bass Boost"],
    photo: ["boseQC45.png", "sonyWH1000XM5.png", "jblFlip6.png"],
  },
  stylingTools: {
    brand: ["Dyson", "Philips", "Remington"],
    model: ["Airwrap", "Prestige", "Pearl Pro"],
    price: [549, 249, 79],
    features: ["Multiple Attachments", "Ionic Technology", "Fast Drying"],
    photo: ["dysonAirwrap.png", "philipsPrestige.png", "remingtonPearlPro.png"],
  },
  gamingConsoles: {
    brand: ["Sony", "Microsoft", "Nintendo"],
    model: ["PlayStation 5", "Xbox Series X", "Switch OLED"],
    price: [499, 499, 349],
    features: ["4K Gaming", "Ray Tracing", "Exclusive Titles"],
    photo: ["ps5.png", "xboxSeriesX.png", "switchOLED.png"],
  },
  stoves: {
    brand: ["Bosch", "Samsung", "LG"],
    model: ["Serie 8", "Flex Duo", "ThinQ"],
    price: [1099, 999, 899],
    features: ["Induction", "Smart Cooking", "Self-Cleaning"],
    photo: ["boschSerie8.png", "samsungFlexDuo.png", "lgThinQ.png"],
  },
  tourism: {
    brand: ["Deuter", "North Face", "Osprey"],
    model: ["Futura 32", "Base Camp", "Atmos AG"],
    price: [159, 199, 279],
    features: ["Waterproof", "Lightweight", "Ergonomic Design"],
    photo: ["deuterFutura32.png", "northFaceBaseCamp.png", "ospreyAtmosAG.png"],
  },
  homeLiving: {
    brand: ["IKEA", "Philips", "Dyson"],
    model: ["Kallax", "Hue", "V11"],
    price: [99, 199, 599],
    features: ["Modular", "Smart Lighting", "Cordless"],
    photo: ["ikeaKallax.png", "philipsHue.png", "dysonV11.png"],
  },
  forChildren: {
    brand: ["LEGO", "Fisher-Price", "Chicco"],
    model: ["Classic Set", "Laugh & Learn", "Next2Me"],
    price: [49, 39, 199],
    features: ["Educational", "Safe Materials", "Adjustable"],
    photo: [
      "legoClassic.png",
      "fisherPriceLaughLearn.png",
      "chiccoNext2Me.png",
    ],
  },
  perfumes: {
    brand: ["Dior", "Chanel", "Armani"],
    model: ["Sauvage", "Coco Mademoiselle", "Acqua di Gio"],
    price: [89, 119, 99],
    features: ["Long Lasting", "Elegant Scent", "Luxury Packaging"],
    photo: ["diorSauvage.png", "chanelCoco.png", "armaniAcquaDiGio.png"],
  },
};
